version: '3'

services: 
  consul:
    image: consul
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0"
    volumes:
      - ./volumes/consul/data:/consul/data
    networks:
      - network
  neo4j:
    image: neo4j:4.4-community
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./volumes/neo4j/conf:/conf
      - ./volumes/neo4j/data:/data
      - ./volumes/neo4j/import:/import
      - ./volumes/neo4j/logs:/logs
      - ./volumes/neo4j/plugins:/plugins
  api_gateway:
    build:
      context: ./api_gateway/
      dockerfile: Dockerfile
    container_name: api_gateway
    restart: on-failure
    ports:
      - "8000:8000"
    volumes:
      - ./cert:/etc/nginx/cert
      - ./api_gateway/api_gateway.conf:/etc/nginx/conf.d/api_gateway.conf
    networks:
      - network
  auth:
    build: ../auth
    container_name: auth
    restart: always
    depends_on:
      - consul
      - jaeger
    environment:
      - DB=consul
      - DBPORT=8500
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - SECRET_KEY=c8cd5f4392ca571f5e9610c9e27ccab4857b1b39267e6deb54ebb0962be0509cb0234d75cfff63f6d70723d670644c60e32e86dac39574e413a1fc2f8383bf75
      - CERT=/cert.pem
      - KEY=/key.pem
      - CA_CERT=/ca-cert.pem
    volumes:
      - ./cert/auth/cert.pem:/cert.pem
      - ./cert/auth/key.pem:/key.pem
      - ./cert/twitter_ca/ca-cert.pem:/ca-cert.pem
    networks:
      - network
  profile:
    build: ../profile
    container_name: profile
    restart: always
    depends_on:
      - jaeger
    environment:
      - DB=consul
      - DBPORT=8500
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - SECRET_KEY=c8cd5f4392ca571f5e9610c9e27ccab4857b1b39267e6deb54ebb0962be0509cb0234d75cfff63f6d70723d670644c60e32e86dac39574e413a1fc2f8383bf75
    networks:
      - network
  social-graph:
    build: ../social-graph
    container_name: social-graph
    restart: always
    depends_on:
      - jaeger
    environment:
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - SECRET_KEY=c8cd5f4392ca571f5e9610c9e27ccab4857b1b39267e6deb54ebb0962be0509cb0234d75cfff63f6d70723d670644c60e32e86dac39574e413a1fc2f8383bf75
    networks:
      - network
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    networks:
      - network
  collector:
    image: otel/opentelemetry-collector:latest
    container_name: collector
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./api_gateway/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    networks:
      - network

networks:
  network:
    driver: bridge